[server]
host = "127.0.0.1"
port = 3001

[database]
url = "sqlite:./data/blog.db"

[auth]
jwt_secret = "your-jwt-secret-key-here"
admin_token = "admin123456"

[ai]
deepseek_api_key = "your-deepseek-api-key-here"
deepseek_api_url = "https://api.deepseek.com/v1/chat/completions"

[cors]
allowed_origins = ["http://localhost:3000", "http://127.0.0.1:3000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization"]

[storage]
upload_dir = "./uploads"
max_file_size = 10485760
